#include "plot.h"

using namespace std::string_literals;
using namespace Plotypus;

namespace Plotypus
{
    Plot::Plot(const std::string& title) :
        Sheet(title)
    {}

    // ====================================================================== //

    void Plot::checkStyleFamily(PlotStyleFamily newDataViewFamily, const std::vector<PlotStyleFamily> allowedFamilies)
    {
        if      (styleFamily == PlotStyleFamily::Custom)
        {
            return;
        }
        else if (styleFamily == PlotStyleFamily::Undefined)
        {
            if (contains(newDataViewFamily, allowedFamilies))
            {
                styleFamily = newDataViewFamily;
            }
            else
            {
                throw IncompatiblePlotStyle("Cannot add DataView to Plot: plot style not supported by sheet type");
            }
        }
        else if (styleFamily != newDataViewFamily)
        {
            throw IncompatiblePlotStyle("Cannot add DataView to Plot: incompatible plot styles");
        }
    }

    void Plot::reset()
    {
        Sheet::reset();

        styleFamily = PlotStyleFamily::Undefined;
        for (auto dataView : dataViews)
        {
            delete dataView;
        }
        dataViews.clear();

        border          = BORDERS_2D_DEFAULT;
        borderLineStyle = STYLE_ID_DEFAULT;

        aspect          = "noratio";
        fill            = "solid";

        key             = true;
        parametric      = false;
    }

    // ====================================================================== //

    PlotStyleFamily Plot::getStyleFamily() const
    {
        return styleFamily;
    }

    void Plot::setStyleFamily(PlotStyleFamily newStyleFamily)
    {
        if (contains(styleFamily, {PlotStyleFamily::Custom, PlotStyleFamily::Undefined}))
        {
            styleFamily = newStyleFamily;
        }
        else
        {
            throw IncompatiblePlotStyle("Cannot override plot style family");
        }
    }

    const std::vector<DataView*>& Plot::getDataViews() const
    {
        return dataViews;
    }

    DataView& Plot::dataView(const size_t i)
    {
        throwIfInvalidIndex("dataView index", i, dataViews);
        return *dataViews[i];
    }

    // ====================================================================== //

    size_t Plot::getBorder() const
    {
        return border;
    }

    void Plot::setBorder(size_t newBorder)
    {
        border = newBorder;
    }

    size_t Plot::getBorderLineStyle() const
    {
        return borderLineStyle;
    }

    void Plot::setBorderLineStyle(size_t newBorderLineStyle)
    {
        borderLineStyle = newBorderLineStyle;
    }

    bool Plot::getKey() const
    {
        return key;
    }

    void Plot::setKey(bool newKey)
    {
        key = newKey;
    }

    bool Plot::getParametric() const
    {
        return parametric;
    }

    void Plot::setParametric(bool newParametric)
    {
        parametric = newParametric;
    }

    const std::string& Plot::getAspect() const
    {
        return aspect;
    }

    void Plot::setAspect(const std::string& newAspect)
    {
        aspect = newAspect;
    }

    void Plot::setAspectNone()
    {
        aspect = "noratio";
    }

    void Plot::setAspectSquare()
    {
        aspect = "square";
    }

    void Plot::setAspectEqual()
    {
        aspect = "ratio -1";
    }

    void Plot::setAspectRatio(double ratio)
    {
        aspect = "ratio "s + std::to_string(ratio);
    }

    const std::string& Plot::getFill() const
    {
        return fill;
    }

    void Plot::setFill(const std::string& newFill)
    {
        fill = newFill;
    }

    // ====================================================================== //
    // writers

    void Plot::preprocessSheet(const std::string& autoDataFilename, const std::string& extension) const
    {
        Sheet::preprocessSheet(autoDataFilename, extension);

        for (size_t i = 1u; const auto dataView : dataViews)
        {
            if (dataView->getAutoGenerateDataFilename())
            {
                const auto fullOutputFilename = autoDataFilename + "_" + std::to_string(i) + "." + extension;
                dataView->setDataFilename(fullOutputFilename);
            }
            ++i;
        }
    }

    void Plot::writeScriptHead(std::ostream& hFile) const
    {
        Sheet::writeScriptHead(hFile);

        // *INDENT-OFF*
        if (!aspect.empty()) {hFile << "set size " << aspect << std::endl;}
        if (!fill.  empty()) {hFile << "set style fill " << fill << std::endl;}

        if (border == BORDERS_NONE) {hFile << "unset border" << std::endl;}
        else                        {hFile <<   "set border " << border;
                                     hFile << optionalStyleString("linestyle", borderLineStyle);
                                     hFile << std::endl;}
        // *INDENT-ON*

        hFile << "set key " << (key ? "on" : "off") << std::endl;
        hFile << (parametric    ? "" : "un") << "set parametric" << std::endl;
        hFile << std::endl;
    }
}
